#!/usr/bin/env python3
"""Keeps the settings dependency catalogue honest (specs/020-settings-dependencies).

Checks that lib/SettingsDeps/catalogue.json, the code and the tests agree:

  1. every reported entry is implemented by the device (lib/SettingsDeps) and
     by the web UI's preview (web/src/lib/settingsDeps.ts);
  2. every entry is named in at least one native test and one web test;
  3. every reported entry has fixture cases, inactive and in effect;
  4. every constraint's message is the device's and the web UI's (FR-010);
  5. device code that makes one setting's effect depend on another section's
     switch carries a `dep: D-NN` marker naming a catalogue entry, and every
     marker names one (FR-014);
  6. docs/reference/settings-dependencies.md matches the catalogue.

  python3 tools/settings-deps/check.py              # check (CI)
  python3 tools/settings-deps/check.py --write-docs # regenerate the docs page

Standard library only. Exit status 1 lists every problem.
"""

import argparse
import glob
import json
import os
import re
import sys

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
CATALOGUE = "lib/SettingsDeps/catalogue.json"
DEVICE_IMPL = "lib/SettingsDeps/src/SettingsDeps.cpp"
WEB_IMPL = "web/src/lib/settingsDeps.ts"
FIXTURES = "test/fixtures/settings-deps/cases.json"
DOCS = "docs/reference/settings-dependencies.md"
CONSTRAINT_SOURCES = ["lib/ConfigModel/src/ConfigModel.cpp", "web/src/validation/configSchema.ts"]

# Device code scanned for undeclared dependencies and markers.
DEVICE_CODE = ["src/**/*.cpp", "src/**/*.h", "include/**/*.h", "lib/*/src/*.cpp", "lib/*/include/*.h", "tools/demo-core/bridge.cpp"]
# The evaluator itself and the settings model are where dependencies are declared.
SCAN_EXCLUDE = {DEVICE_IMPL, "lib/SettingsDeps/include/SettingsDeps.h", "lib/ConfigModel/src/ConfigModel.cpp"}

ID = re.compile(r"\bD-\d{2}\b")
MARKER = re.compile(r"dep:\s*((?:D-\d{2}\s*)+)")
# A read of a setting's on/off switch: cfg.mqtt.enabled, config.alerts.mqttEnabled, ...
SWITCH = re.compile(
    r"\b(?:cfg|config|getConfigCallback\(\)|bootConfig)\.(\w+)\.(enabled|\w+Enabled|set|armWithAlpaca|homeAssistant|\w+NightOnly|passkey)\b"
)
CONDITION = re.compile(r"\bif\s*\(|&&|\|\||\?")


def read(root, rel):
    with open(os.path.join(root, rel), encoding="utf-8") as f:
        return f.read()


def with_english(root, text):
    """The text with each t('key') call followed by its English (web/src/i18n/en.json): the
    UI's messages are translated, so the shared message lives there (specs/023-i18n)."""
    english = json.loads(read(root, "web/src/i18n/en.json"))
    return text + "\n" + "\n".join(str(english.get(key, "")) for key in re.findall(r"\bt\('([\w.]+)'", text))


def files(root, patterns):
    found = set()
    for pattern in patterns:
        found.update(glob.glob(os.path.join(root, pattern), recursive=True))
    return sorted(os.path.relpath(path, root) for path in found)


def undeclared_dependencies(rel, text):
    """Conditions that read switches of two different settings sections with no
    `dep: D-NN` marker on that line or the two before it."""
    problems = []
    lines = text.splitlines()
    for number, line in enumerate(lines, 1):
        if not CONDITION.search(line):
            continue
        sections = {m.group(1) for m in SWITCH.finditer(line)}
        if len(sections) < 2:
            continue
        nearby = "\n".join(lines[max(0, number - 3) : number])
        if not MARKER.search(nearby):
            problems.append(
                f"{rel}:{number}: depends on {' and '.join(sorted(sections))} switches without a `dep: D-NN` marker "
                f"(declare it in {CATALOGUE})"
            )
    return problems


def markers(text):
    return {i for m in MARKER.finditer(text) for i in ID.findall(m.group(1))}


def docs_page(catalogue):
    rows = []
    for e in catalogue["entries"]:
        reasons = "; ".join(f"{catalogue['reasons'][r]['text']} ({r})" for r in e["reasons"]) or "-"
        behaviour = e["class"].capitalize()
        if e.get("unmet"):
            behaviour += f", {e['unmet']} when unmet"
        if e.get("runtime"):
            behaviour += ", runtime"
        settings = ", ".join(f"`{s}`" for s in e["settings"])
        rows.append(f"| {e['id']} | {settings} | {e['dependsOn']} | {behaviour} | {reasons} |")
    return "\n".join(
        [
            "# Settings dependencies",
            "",
            "<!-- Generated by tools/settings-deps/check.py --write-docs from lib/SettingsDeps/catalogue.json. Don't edit by hand. -->",
            "",
            "Some settings only work when something else is on: MQTT alerts need MQTT, rain alerts need the rain sensor, "
            "night-only alerts need your location. SQMeter keeps such a setting exactly as you saved it, but while what it "
            "needs is missing the setting is **inactive**: the device doesn't act on it, Settings shows why with a "
            "one-click fix, and [`GET /api/settings/effective`](../api/rest.md#get-apisettingseffective) reports it.",
            "",
            "- **Dependency**: kept and reported inactive until what it needs is there.",
            "- **Constraint**: a combination that can never work; the save is refused with the device's message.",
            "- **Runtime**: depends on WiFi, the broker, the clock, a GPS fix or a restart rather than on a setting - it never stops you switching the setting on.",
            "- **fail-safe** safety rules report unsafe while their sensor is off or missing; **inactive** ones are listed under `rulesNotInEffect` in the safety document.",
            "",
            "| ID | Setting | Needs | Kind | Shown as |",
            "|---|---|---|---|---|",
            *rows,
            "",
        ]
    )


def check_structure(catalogue):
    """IDs unique; class, kind and reasons valid; constraints list their messages."""
    problems, seen = [], set()
    for e in catalogue["entries"]:
        if e["id"] in seen:
            problems.append(f"{CATALOGUE}: {e['id']} is listed twice")
        seen.add(e["id"])
        if e["class"] not in ("dependency", "constraint"):
            problems.append(f"{CATALOGUE}: {e['id']} class must be dependency or constraint")
        if e["kind"] not in ("setting", "feature"):
            problems.append(f"{CATALOGUE}: {e['id']} kind must be setting or feature")
        if e["class"] == "constraint" and (e["kind"] != "feature" or not e.get("messages")):
            problems.append(f"{CATALOGUE}: constraint {e['id']} must be kind feature and list its messages")
        problems += [f"{CATALOGUE}: {e['id']} uses unknown reason {r}" for r in e["reasons"] if r not in catalogue["reasons"]]
    return problems


def load_sources(root):
    """Everything the entries are checked against."""
    web_test_patterns = ["web/src/**/__tests__/**/*.ts", "web/src/**/__tests__/**/*.tsx", "web/src/**/*.test.ts", "web/src/**/*.test.tsx"]
    return {
        "device": read(root, DEVICE_IMPL),
        "web": read(root, WEB_IMPL),
        "native_tests": "\n".join(read(root, f) for f in files(root, ["test/**/*.cpp"])),
        "web_tests": "\n".join(read(root, f) for f in files(root, web_test_patterns)),
        "constraints": {source: with_english(root, read(root, source)) for source in CONSTRAINT_SOURCES},
    }


def check_code(root, known_ids):
    """Markers name catalogue entries; no undeclared dependencies. Returns (problems, marked IDs)."""
    problems, marked = [], set()
    for rel in files(root, DEVICE_CODE):
        if rel in SCAN_EXCLUDE:
            continue
        text = read(root, rel)
        found = markers(text)
        problems += [f"{rel}: marker names {unknown}, which isn't in {CATALOGUE}" for unknown in sorted(found - known_ids)]
        marked |= found
        problems += undeclared_dependencies(rel, text)
    return problems, marked


def fixture_coverage(fixtures):
    """IDs some fixture case makes inactive, and settings some case has in effect."""
    inactive_ids, effective_settings = set(), set()
    for case in fixtures["cases"]:
        for setting, expected in case["expect"].items():
            if expected and expected["state"] == "inactive":
                inactive_ids.add(expected["id"])
            elif expected and expected["state"] == "active":
                effective_settings.add(setting)
    return inactive_ids, effective_settings


def check_implemented(e, sources, coverage, marked):
    """A reported entry is in both evaluators and the fixtures; a feature dependency is marked in the code."""
    i = e["id"]
    if e["kind"] != "setting":
        needs_marker = e["class"] == "dependency" and i not in marked
        return [f"{i}: a feature dependency needs a `dep: {i}` marker where the device enforces it"] if needs_marker else []
    inactive_ids, effective_settings = coverage
    problems = []
    if f'"{i}"' not in sources["device"]:
        problems.append(f"{i}: not implemented in {DEVICE_IMPL}")
    if f"'{i}'" not in sources["web"]:
        problems.append(f"{i}: not implemented in {WEB_IMPL}")
    if e["reasons"] and i not in inactive_ids:
        problems.append(f"{i}: no fixture case where it makes a setting inactive ({FIXTURES})")
    if not set(e["settings"]) & effective_settings:
        problems.append(f"{i}: no fixture case where its setting is in effect ({FIXTURES})")
    return problems


def check_tested(e, sources):
    """Named in a native and a web test; constraint messages shared by the device and the UI (FR-010)."""
    i = e["id"]
    problems = [
        f"{i}: message {message!r} not in {source} (FR-010: the same message on the device and in the UI)"
        for message in e.get("messages", [])
        for source, text in sources["constraints"].items()
        if message not in text
    ]
    if i not in sources["native_tests"]:
        problems.append(f"{i}: no native test names it (test/)")
    if i not in sources["web_tests"]:
        problems.append(f"{i}: no web test names it (web/src)")
    return problems


def check_docs(root, catalogue, write_docs):
    page = docs_page(catalogue)
    if write_docs:
        with open(os.path.join(root, DOCS), "w", encoding="utf-8") as f:
            f.write(page)
        return []
    if not os.path.exists(os.path.join(root, DOCS)) or read(root, DOCS) != page:
        return [f"{DOCS} is out of date: run python3 tools/settings-deps/check.py --write-docs"]
    return []


def check(root, write_docs=False):
    catalogue = json.loads(read(root, CATALOGUE))
    problems = check_structure(catalogue)
    sources = load_sources(root)
    code_problems, marked = check_code(root, {e["id"] for e in catalogue["entries"]})
    problems += code_problems
    coverage = fixture_coverage(json.loads(read(root, FIXTURES)))
    for e in catalogue["entries"]:
        problems += check_implemented(e, sources, coverage, marked)
        problems += check_tested(e, sources)
    return problems + check_docs(root, catalogue, write_docs)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--root", default=ROOT, help="repository root")
    parser.add_argument("--write-docs", action="store_true", help=f"regenerate {DOCS}")
    args = parser.parse_args(argv)
    problems = check(args.root, args.write_docs)
    for problem in problems:
        print(f"settings-deps: {problem}")
    if problems:
        print(f"settings-deps: {len(problems)} problem(s)")
        return 1
    print("settings-deps: catalogue, code, tests and docs agree")
    return 0


if __name__ == "__main__":
    sys.exit(main())
