// What each dependent setting is called in Settings, for the "Saving makes
// these inactive" preview (specs/020-settings-dependencies).
export const DEP_LABELS: Record<string, string> = {
  'alerts.pushover.enabled': 'Pushover alerts',
  'alerts.ntfy.enabled': 'ntfy alerts',
  'alerts.webhook.enabled': 'Webhook alerts',
  'alerts.mqtt.enabled': 'MQTT alerts',
  'alerts.events.unsafe.level': '"It turns unsafe" alerts',
  'alerts.events.safe.level': '"It\'s safe again" alerts',
  'alerts.events.rain_started.level': '"Rain starts" alerts',
  'alerts.events.rain_stopped.level': '"Rain stops" alerts',
  'alerts.events.sensor_fault.level': '"A sensor fails" alerts',
  'alerts.events.sensor_recovered.level': '"A sensor recovers" alerts',
  'alerts.events.dew_risk.level': '"Dew risk" alerts',
  'alerts.events.clear_sky.level': '"Skies clear up" alerts',
  'alerts.events.clouded_over.level': '"Skies cloud over" alerts',
  'alerts.wakePhones': 'Ringing paired phones',
  'alerts.skyNightOnly': 'Sky alerts only when dark',
  'alerts.safetyNightOnly': 'Safety alerts only when dark',
  'alerts.nightSunAltitudeDeg': 'Dark means',
  'alerts.sendMode': 'Only while an imaging app is connected',
  'alerts.events.client_lost.level': '"The imaging app stops checking" alerts',
  'alerts.events.client_back.level': '"The imaging app is back" alerts',
  'alerts.events.client_disconnected.level': '"The imaging app disconnects" alerts',
  'mqtt.homeAssistant.enabled': 'Home Assistant discovery',
  'mqtt.homeAssistant.alertsSwitch': 'Home Assistant alerts switch',
  'mqtt.publish.gps': 'Publishing GPS',
  'mqtt.publish.rain': 'Publishing rain',
  'mqtt.publish.wind': 'Publishing wind',
  'alpaca.rainUnsafeEnabled': 'Unsafe while raining',
  'alpaca.rainSensorRequired': 'Unsafe if the rain sensor fails',
  'alpaca.windSpeedUnsafeEnabled': 'Max wind speed',
  'alpaca.windGustUnsafeEnabled': 'Max gust',
  'alpaca.cloudCoverEnabled': 'Max cloud cover',
  'alpaca.sqmMinEnabled': 'Min sky darkness',
  'alpaca.humidityMaxEnabled': 'Max humidity',
  'alpaca.dewpointMarginEnabled': 'Min margin above dew point',
  'wind.directionEnabled': 'Wind vane',
  'rain.dailyResetEnabled': 'Daily rain total reset',
  'location.showSunMoon': 'Sun & Moon card',
  'gps.enabled': 'GPS',
  'ntp.enabled': 'Internet time (NTP)',
  'skyCalibration.enabled': 'Sky calibration',
  'ble.enabled': 'Bluetooth',
  'ble.phoneAlarm': 'Phone alarm',
  'ota.enabled': 'Command-line uploads',
  'wifi.mdns': 'mDNS',
};
