import { t } from '../../i18n';
// What each dependent setting is called in Settings, for the "Saving makes
// these inactive" preview (specs/020-settings-dependencies).
export const DEP_LABELS: Record<string, string> = {
  'alerts.pushover.enabled': t('settings.depLabels.pushoverAlerts'),
  'alerts.ntfy.enabled': t('settings.depLabels.ntfyAlerts'),
  'alerts.webhook.enabled': t('settings.depLabels.webhookAlerts'),
  'alerts.mqtt.enabled': t('settings.depLabels.mqttAlerts'),
  'alerts.events.unsafe.level': t('settings.depLabels.itTurnsUnsafeAlerts'),
  'alerts.events.safe.level': t('settings.depLabels.itSSafeAgainAlerts'),
  'alerts.events.rain_started.level': t('settings.depLabels.rainStartsAlerts'),
  'alerts.events.rain_stopped.level': t('settings.depLabels.rainStopsAlerts'),
  'alerts.events.sensor_fault.level': t('settings.depLabels.aSensorFailsAlerts'),
  'alerts.events.sensor_recovered.level': t('settings.depLabels.aSensorRecoversAlerts'),
  'alerts.events.dew_risk.level': t('settings.depLabels.dewRiskAlerts'),
  'alerts.events.clear_sky.level': t('settings.depLabels.skiesClearUpAlerts'),
  'alerts.events.clouded_over.level': t('settings.depLabels.skiesCloudOverAlerts'),
  'alerts.wakePhones': t('settings.depLabels.ringingPairedPhones'),
  'alerts.skyNightOnly': t('settings.depLabels.skyAlertsOnlyWhenDark'),
  'alerts.safetyNightOnly': t('settings.depLabels.safetyAlertsOnlyWhenDark'),
  'alerts.nightSunAltitudeDeg': t('settings.depLabels.darkMeans'),
  'alerts.sendMode': t('settings.depLabels.onlyWhileAnImagingApp'),
  'alerts.events.client_lost.level': t('settings.depLabels.theImagingAppStopsChecking'),
  'alerts.events.client_back.level': t('settings.depLabels.theImagingAppIsBack'),
  'alerts.events.client_disconnected.level': t('settings.depLabels.theImagingAppDisconnectsAlerts'),
  'mqtt.homeAssistant.enabled': t('settings.depLabels.homeAssistantDiscovery'),
  'mqtt.homeAssistant.alertsSwitch': t('settings.depLabels.homeAssistantAlertsSwitch'),
  'mqtt.publish.gps': t('settings.depLabels.publishingGps'),
  'mqtt.publish.rain': t('settings.depLabels.publishingRain'),
  'mqtt.publish.wind': t('settings.depLabels.publishingWind'),
  'alpaca.rainUnsafeEnabled': t('settings.depLabels.unsafeWhileRaining'),
  'alpaca.rainSensorRequired': t('settings.depLabels.unsafeIfTheRainSensor'),
  'alpaca.windSpeedUnsafeEnabled': t('settings.depLabels.maxWindSpeed'),
  'alpaca.windGustUnsafeEnabled': t('settings.depLabels.maxGust'),
  'alpaca.cloudCoverEnabled': t('settings.depLabels.maxCloudCover'),
  'alpaca.sqmMinEnabled': t('settings.depLabels.minSkyDarkness'),
  'alpaca.humidityMaxEnabled': t('settings.depLabels.maxHumidity'),
  'alpaca.dewpointMarginEnabled': t('settings.depLabels.minMarginAboveDewPoint'),
  'wind.directionEnabled': t('settings.depLabels.windVane'),
  'rain.dailyResetEnabled': t('settings.depLabels.dailyRainTotalReset'),
  'location.showSunMoon': t('settings.depLabels.sunMoonCard'),
  'gps.enabled': 'GPS',
  'ntp.enabled': t('settings.depLabels.internetTimeNtp'),
  'skyCalibration.enabled': t('settings.depLabels.skyCalibration'),
  'ble.enabled': t('settings.depLabels.bluetooth'),
  'ble.phoneAlarm': t('settings.depLabels.phoneAlarm'),
  'ota.enabled': t('settings.depLabels.commandLineUploads'),
  'wifi.mdns': 'mDNS',
};
