import { mockConfig } from '../mocks/data';
import type { DepFacts } from '../lib/settingsDeps';

// One row per catalogued dependency the Settings UI shows (specs/020-settings-dependencies, FR-013b);
// used by components/__tests__/SettingsDependencies.test.tsx.
export const alerts = mockConfig.alerts!;
export const level = (key: keyof typeof alerts.events, value: number) => ({
  ...alerts.events,
  [key]: { ...alerts.events[key], level: value },
});
export const mqttOn = { ...mockConfig.mqtt, enabled: true, broker: '192.168.1.10', topic: 'sqmeter' };
export const mqttOff = { ...mockConfig.mqtt, enabled: false };

export type Case = {
  id: string;
  tab: string;
  config?: Record<string, unknown>;
  facts?: Partial<DepFacts>;
  note: string; // exact note text
  control?: string; // checkbox or select label
  control_state?: 'locked' | 'unlocked';
  fixLabel?: string;
  fixTab?: string; // the tab the fix lands on
};

export const CASES: Case[] = [
  {
    id: 'D-01',
    tab: 'alerts',
    config: { mqtt: mqttOff, alerts: { ...alerts, mqtt: { enabled: true } } },
    note: 'Inactive - MQTT is off',
    control: 'MQTT',
    control_state: 'unlocked',
    fixLabel: 'Turn on MQTT',
    fixTab: 'Network',
  },
  {
    id: 'D-01',
    tab: 'alerts',
    config: { mqtt: mqttOff, alerts: { ...alerts, mqtt: { enabled: false } } },
    note: 'MQTT is off.',
    control: 'MQTT',
    control_state: 'locked',
  },
  {
    id: 'D-02',
    tab: 'alerts',
    config: { mqtt: mqttOn, alerts: { ...alerts, mqtt: { enabled: true } } },
    facts: { mqttConnected: false },
    note: 'Inactive - Broker not connected',
    control: 'MQTT',
    control_state: 'unlocked',
  },
  {
    id: 'D-03',
    tab: 'alerts',
    config: { alerts: { ...alerts, ntfy: { ...alerts.ntfy, enabled: true } } },
    facts: { wifiConnected: false },
    note: 'Inactive - Not connected to WiFi',
    control: 'ntfy',
    control_state: 'unlocked',
    fixLabel: 'WiFi settings',
    fixTab: 'Network',
  },
  {
    id: 'D-05',
    tab: 'alerts',
    config: { rain: { ...mockConfig.rain, enabled: false }, alerts: { ...alerts, events: level('rain_started', 0) } },
    note: 'Rain sensor is off.',
    control: 'Rain starts: level',
    control_state: 'locked',
    fixLabel: 'Turn on',
    fixTab: 'Sensors',
  },
  {
    id: 'D-05',
    tab: 'alerts',
    config: {
      rain: { ...mockConfig.rain, enabled: false },
      alerts: { ...alerts, events: { ...level('rain_started', 2), rain_stopped: { level: 0, sound: '' } } },
    },
    note: 'Inactive - Rain sensor is off',
    control: 'Rain starts: level',
    control_state: 'unlocked',
  },
  {
    id: 'D-06',
    tab: 'alerts',
    config: { alerts: { ...alerts, events: level('dew_risk', 2) } },
    facts: { environmentDetected: false },
    note: 'Inactive - BME280 not detected',
    control: 'Dew risk within: level',
    control_state: 'unlocked',
    fixLabel: 'Sky sensors',
    fixTab: 'Sensors',
  },
  {
    id: 'D-07',
    tab: 'alerts',
    config: { alerts: { ...alerts, events: { ...level('clouded_over', 2), clear_sky: { level: 0, sound: '' } } } },
    facts: { infraredDetected: false },
    note: 'Inactive - MLX90614 not detected',
    control: 'Skies cloud over above: level',
    control_state: 'unlocked',
  },
  {
    id: 'D-08',
    tab: 'alerts',
    config: { alerts: { ...alerts, events: level('unsafe', 4) } },
    note: "Phones won't ring - Needs the Bluetooth firmware build",
    fixLabel: 'Bluetooth',
    fixTab: 'Device',
  },
  {
    id: 'D-09',
    tab: 'alerts',
    config: { location: { set: false, latitude: 0, longitude: 0 }, alerts: { ...alerts, skyNightOnly: true, safetyNightOnly: false } },
    facts: { gpsFix: false },
    note: 'Inactive - Needs your location',
    control: "Sky alerts only when it's dark",
    control_state: 'unlocked',
    fixLabel: 'Set location',
    fixTab: 'Time & Location',
  },
  {
    id: 'D-10',
    tab: 'alerts',
    config: { location: { set: false, latitude: 0, longitude: 0 }, alerts: { ...alerts, skyNightOnly: true, safetyNightOnly: false } },
    facts: { gpsFix: false },
    note: 'Needs your location.',
    control: "Safety alerts only when it's dark",
    control_state: 'locked',
  },
  {
    id: 'D-12',
    tab: 'alerts',
    config: { alpaca: { ...mockConfig.alpaca, enabled: false }, alerts: { ...alerts, armWithAlpaca: true } },
    note: 'Inactive - Alpaca is off',
    control: 'On while N.I.N.A. is connected',
    control_state: 'unlocked',
    fixLabel: 'Turn on Alpaca',
    fixTab: 'Safety',
  },
  {
    id: 'D-13',
    tab: 'network',
    config: {
      mqtt: { ...mqttOn, homeAssistant: { enabled: true, discoveryPrefix: 'homeassistant' } },
      alerts: { ...alerts, enabled: false },
    },
    note: 'No alerts switch - Alerts are off',
    fixLabel: 'Turn on alerts',
    fixTab: 'Alerts',
  },
  {
    id: 'D-14',
    tab: 'network',
    config: { mqtt: { ...mqttOn, publish: { ...mqttOn.publish, rain: true } }, rain: { ...mockConfig.rain, enabled: false } },
    note: 'Nothing to publish - Rain sensor is off',
    control: 'Rain',
    control_state: 'unlocked',
  },
  {
    id: 'D-15',
    tab: 'safety',
    config: {
      rain: { ...mockConfig.rain, enabled: false },
      alpaca: { ...mockConfig.alpaca, rainUnsafeEnabled: true, rainSensorRequired: false },
    },
    note: 'Not in effect - Rain sensor is off',
    control: 'Unsafe while raining',
    control_state: 'unlocked',
    fixLabel: 'Turn on',
    fixTab: 'Sensors',
  },
  {
    id: 'D-16',
    tab: 'safety',
    config: {
      wind: { ...mockConfig.wind, enabled: false },
      alpaca: { ...mockConfig.alpaca, windSpeedUnsafeEnabled: true, windGustUnsafeEnabled: false },
    },
    note: 'Reports unsafe - Anemometer is off',
    control: 'Max wind speed',
    control_state: 'unlocked',
  },
  {
    id: 'D-17',
    tab: 'safety',
    config: { alpaca: { ...mockConfig.alpaca, cloudCoverEnabled: true } },
    facts: { infraredDetected: false },
    note: 'Reports unsafe - MLX90614 not detected',
    control: 'Max cloud cover',
    control_state: 'unlocked',
  },
  {
    id: 'D-18',
    tab: 'safety',
    config: { alpaca: { ...mockConfig.alpaca, sqmMinEnabled: false } },
    facts: { lightDetected: false },
    note: 'TSL2591 not detected.',
    control: 'Min sky darkness',
    control_state: 'locked',
  },
  {
    id: 'D-19',
    tab: 'safety',
    config: { alpaca: { ...mockConfig.alpaca, humidityMaxEnabled: true, dewpointMarginEnabled: false } },
    facts: { environmentDetected: false },
    note: 'Reports unsafe - BME280 not detected',
    control: 'Max humidity',
    control_state: 'unlocked',
  },
  {
    id: 'D-24',
    tab: 'sensors',
    config: { rain: { ...mockConfig.rain, enabled: true, dailyResetEnabled: true } },
    facts: { clockSet: false },
    note: "Inactive - The device doesn't know the time yet",
    control: 'Reset the daily total',
    control_state: 'unlocked',
    fixLabel: 'Time sources',
    fixTab: 'Time & Location',
  },
  {
    id: 'D-25',
    tab: 'time',
    config: { location: { set: false, latitude: 0, longitude: 0, showSunMoon: true } },
    facts: { gpsFix: false },
    note: 'Inactive - Needs your location',
    control: 'Sun & Moon card on the dashboard',
    control_state: 'unlocked',
  },
  {
    id: 'D-26',
    tab: 'time',
    config: { gps: { ...mockConfig.gps, enabled: true } },
    facts: { gpsFix: false },
    note: 'Inactive - No GPS fix - using the location in Settings',
    control: 'GPS receiver',
    control_state: 'unlocked',
  },
  {
    id: 'D-28',
    tab: 'time',
    config: { ntp: { ...mockConfig.ntp, enabled: true } },
    facts: { wifiConnected: false },
    note: 'Inactive - Not connected to WiFi',
    fixLabel: 'WiFi settings',
    fixTab: 'Network',
  },
  {
    id: 'D-29',
    tab: 'sensors',
    config: { skyCalibration: { ...mockConfig.skyCalibration, enabled: false } },
    facts: { lightDetected: false },
    note: 'TSL2591 not detected.',
    control: 'Apply SQM offset',
    control_state: 'locked',
  },
  {
    id: 'D-32',
    tab: 'device',
    config: { ota: { enabled: true, password: '' } },
    note: 'Inactive - Set an upload password',
    control: 'Command-line uploads (ArduinoOTA)',
    control_state: 'unlocked',
  },
  {
    id: 'D-35',
    tab: 'time',
    config: { gps: { ...mockConfig.gps, enabled: true } },
    facts: { gpsRunning: false, gpsFix: false },
    note: 'Inactive - GPS starts after a restart',
    control: 'GPS receiver',
    control_state: 'unlocked',
    fixLabel: 'Restart',
  },
  // Can't be switched on while what it needs is off or missing (FR-005).
  {
    id: 'D-12',
    tab: 'alerts',
    config: { alpaca: { ...mockConfig.alpaca, enabled: false }, alerts: { ...alerts, armWithAlpaca: false } },
    note: 'Alpaca is off.',
    control: 'On while N.I.N.A. is connected',
    control_state: 'locked',
  },
  {
    id: 'D-14',
    tab: 'network',
    config: { mqtt: { ...mqttOn, publish: { ...mqttOn.publish, rain: false } }, rain: { ...mockConfig.rain, enabled: false } },
    note: 'Rain sensor is off.',
    control: 'Rain',
    control_state: 'locked',
  },
  {
    id: 'D-15',
    tab: 'safety',
    config: { rain: { ...mockConfig.rain, enabled: false }, alpaca: { ...mockConfig.alpaca, rainUnsafeEnabled: false } },
    note: 'Rain sensor is off.',
    control: 'Unsafe while raining',
    control_state: 'locked',
  },
  {
    id: 'D-16',
    tab: 'safety',
    config: { wind: { ...mockConfig.wind, enabled: false }, alpaca: { ...mockConfig.alpaca, windSpeedUnsafeEnabled: false } },
    note: 'Anemometer is off.',
    control: 'Max wind speed',
    control_state: 'locked',
  },
  {
    id: 'D-17',
    tab: 'safety',
    config: { alpaca: { ...mockConfig.alpaca, cloudCoverEnabled: false } },
    facts: { infraredDetected: false },
    note: 'MLX90614 not detected.',
    control: 'Max cloud cover',
    control_state: 'locked',
  },
  {
    id: 'D-19',
    tab: 'safety',
    config: { alpaca: { ...mockConfig.alpaca, humidityMaxEnabled: false } },
    facts: { environmentDetected: false },
    note: 'BME280 not detected.',
    control: 'Max humidity',
    control_state: 'locked',
  },
  {
    id: 'D-25',
    tab: 'time',
    config: { location: { set: false, latitude: 0, longitude: 0, showSunMoon: false } },
    facts: { gpsFix: false },
    note: 'Needs your location.',
    control: 'Sun & Moon card on the dashboard',
    control_state: 'locked',
  },
  {
    id: 'D-36',
    tab: 'network',
    config: { wifi: { ...mockConfig.wifi, mdns: true } },
    facts: { wifiConnected: false },
    note: 'Inactive - Not connected to WiFi',
    control: 'Advertise on the network (mDNS)',
    control_state: 'unlocked',
  },
];
